runtime: python39
api_version: 1
threadsafe: 1

libraries:
  - name: django
    version: "1.5"
  - name: MySQLdb
    version: "latest"
  - name: jinja2
    version: "latest"

builtins:
  - django_wsgi: on